mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://doh.dns.sb/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - name: Proxy1
    type: ss
    server: 54.169.26.131
    port: "13341"
    cipher: chacha20-ietf-poly1305
    password: kZX3GZkWstiviwCAY0ibCj
  - name: Proxy2
    type: vmess
    server: shouer1.209966.xyz
    port: "14338"
    uuid: 7fd4d16d-4b6b-4560-cf6c-23fa094be476
    alterId: "0"
    cipher: auto
proxy-groups:
  - name: myNet
    type: select
    proxies:
      - Proxy1
      - Proxy2
rules:
  - DOMAIN,beiyong.myNetcn.com,DIRECT
  - DOMAIN-SUFFIX,services.googleapis.cn,myNet
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,myNet
  - DOMAIN,safebrowsing.urlsec.qq.com,DIRECT
  - DOMAIN,safebrowsing.googleapis.com,DIRECT
  - DOMAIN,developer.apple.com,myNet
  - DOMAIN-SUFFIX,digicert.com,myNet
  - DOMAIN,ocsp.apple.com,myNet
  - DOMAIN,ocsp.comodoca.com,myNet
  - DOMAIN,ocsp.usertrust.com,myNet
  - DOMAIN,ocsp.sectigo.com,myNet
  - DOMAIN,ocsp.verisign.net,myNet
  - DOMAIN-SUFFIX,apple-dns.net,myNet
  - DOMAIN,testflight.apple.com,myNet
  - DOMAIN,sandbox.itunes.apple.com,myNet
  - DOMAIN,itunes.apple.com,myNet
  - DOMAIN-SUFFIX,apps.apple.com,myNet
  - DOMAIN-SUFFIX,blobstore.apple.com,myNet
  - DOMAIN,cvws.icloud-content.com,myNet
  - DOMAIN-SUFFIX,mzstatic.com,DIRECT
  - DOMAIN-SUFFIX,itunes.apple.com,DIRECT
  - DOMAIN-SUFFIX,icloud.com,DIRECT
  - DOMAIN-SUFFIX,icloud-content.com,DIRECT
  - DOMAIN-SUFFIX,me.com,DIRECT
  - DOMAIN-SUFFIX,aaplimg.com,DIRECT
  - DOMAIN-SUFFIX,cdn20.com,DIRECT
  - DOMAIN-SUFFIX,cdn-apple.com,DIRECT
  - DOMAIN-SUFFIX,akadns.net,DIRECT
  - DOMAIN-SUFFIX,akamaiedge.net,DIRECT
  - DOMAIN-SUFFIX,edgekey.net,DIRECT
  - DOMAIN-SUFFIX,mwcloudcdn.com,DIRECT
  - DOMAIN-SUFFIX,mwcname.com,DIRECT
  - DOMAIN-SUFFIX,apple.com,DIRECT
  - DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
  - DOMAIN-SUFFIX,apple-mapkit.com,DIRECT
  - DOMAIN-SUFFIX,126.com,DIRECT
  - DOMAIN-SUFFIX,126.net,DIRECT
  - DOMAIN-SUFFIX,127.net,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,360buyimg.com,DIRECT
  - DOMAIN-SUFFIX,36kr.com,DIRECT
  - DOMAIN-SUFFIX,acfun.tv,DIRECT
  - DOMAIN-SUFFIX,air-matters.com,DIRECT
  - DOMAIN-SUFFIX,aixifan.com,DIRECT
  - DOMAIN-KEYWORD,alicdn,DIRECT
  - DOMAIN-KEYWORD,alipay,DIRECT
  - DOMAIN-KEYWORD,taobao,DIRECT
  - DOMAIN-SUFFIX,amap.com,DIRECT
  - DOMAIN-SUFFIX,autonavi.com,DIRECT
  - DOMAIN-KEYWORD,baidu,DIRECT
  - DOMAIN-SUFFIX,bdimg.com,DIRECT
  - DOMAIN-SUFFIX,bdstatic.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,caiyunapp.com,DIRECT
  - DOMAIN-SUFFIX,clouddn.com,DIRECT
  - DOMAIN-SUFFIX,cnbeta.com,DIRECT
  - DOMAIN-SUFFIX,cnbetacdn.com,DIRECT
  - DOMAIN-SUFFIX,cootekservice.com,DIRECT
  - DOMAIN-SUFFIX,csdn.net,DIRECT
  - DOMAIN-SUFFIX,ctrip.com,DIRECT
  - DOMAIN-SUFFIX,dgtle.com,DIRECT
  - DOMAIN-SUFFIX,dianping.com,DIRECT
  - DOMAIN-SUFFIX,douban.com,DIRECT
  - DOMAIN-SUFFIX,doubanio.com,DIRECT
  - DOMAIN-SUFFIX,duokan.com,DIRECT
  - DOMAIN-SUFFIX,easou.com,DIRECT
  - DOMAIN-SUFFIX,ele.me,DIRECT
  - DOMAIN-SUFFIX,feng.com,DIRECT
  - DOMAIN-SUFFIX,fir.im,DIRECT
  - DOMAIN-SUFFIX,frdic.com,DIRECT
  - DOMAIN-SUFFIX,g-cores.com,DIRECT
  - DOMAIN-SUFFIX,godic.net,DIRECT
  - DOMAIN-SUFFIX,gtimg.com,DIRECT
  - DOMAIN,cdn.hockeyapp.net,DIRECT
  - DOMAIN-SUFFIX,hongxiu.com,DIRECT
  - DOMAIN-SUFFIX,hxcdn.net,DIRECT
  - DOMAIN-SUFFIX,iciba.com,DIRECT
  - DOMAIN-SUFFIX,ifeng.com,DIRECT
  - DOMAIN-SUFFIX,ifengimg.com,DIRECT
  - DOMAIN-SUFFIX,ipip.net,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,jianshu.com,DIRECT
  - DOMAIN-SUFFIX,knewone.com,DIRECT
  - DOMAIN-SUFFIX,le.com,DIRECT
  - DOMAIN-SUFFIX,lecloud.com,DIRECT
  - DOMAIN-SUFFIX,lemicp.com,DIRECT
  - DOMAIN-SUFFIX,licdn.com,DIRECT
  - DOMAIN-SUFFIX,luoo.net,DIRECT
  - DOMAIN-SUFFIX,meituan.com,DIRECT
  - DOMAIN-SUFFIX,meituan.net,DIRECT
  - DOMAIN-SUFFIX,mi.com,DIRECT
  - DOMAIN-SUFFIX,miaopai.com,DIRECT
  - DOMAIN-SUFFIX,microsoft.com,DIRECT
  - DOMAIN-SUFFIX,microsoftonline.com,DIRECT
  - DOMAIN-SUFFIX,miui.com,DIRECT
  - DOMAIN-SUFFIX,miwifi.com,DIRECT
  - DOMAIN-SUFFIX,mob.com,DIRECT
  - DOMAIN-SUFFIX,netease.com,DIRECT
  - DOMAIN-SUFFIX,office.com,DIRECT
  - DOMAIN-SUFFIX,office365.com,DIRECT
  - DOMAIN-KEYWORD,officecdn,DIRECT
  - DOMAIN-SUFFIX,oschina.net,DIRECT
  - DOMAIN-SUFFIX,ppsimg.com,DIRECT
  - DOMAIN-SUFFIX,pstatp.com,DIRECT
  - DOMAIN-SUFFIX,qcloud.com,DIRECT
  - DOMAIN-SUFFIX,qdaily.com,DIRECT
  - DOMAIN-SUFFIX,qdmm.com,DIRECT
  - DOMAIN-SUFFIX,qhimg.com,DIRECT
  - DOMAIN-SUFFIX,qhres.com,DIRECT
  - DOMAIN-SUFFIX,qidian.com,DIRECT
  - DOMAIN-SUFFIX,qihucdn.com,DIRECT
  - DOMAIN-SUFFIX,qiniu.com,DIRECT
  - DOMAIN-SUFFIX,qiniucdn.com,DIRECT
  - DOMAIN-SUFFIX,qiyipic.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,qqurl.com,DIRECT
  - DOMAIN-SUFFIX,rarbg.to,DIRECT
  - DOMAIN-SUFFIX,ruguoapp.com,DIRECT
  - DOMAIN-SUFFIX,segmentfault.com,DIRECT
  - DOMAIN-SUFFIX,sinaapp.com,DIRECT
  - DOMAIN-SUFFIX,smzdm.com,DIRECT
  - DOMAIN-SUFFIX,snapdrop.net,DIRECT
  - DOMAIN-SUFFIX,sogou.com,DIRECT
  - DOMAIN-SUFFIX,sogoucdn.com,DIRECT
  - DOMAIN-SUFFIX,sohu.com,DIRECT
  - DOMAIN-SUFFIX,soku.com,DIRECT
  - DOMAIN-SUFFIX,speedtest.net,DIRECT
  - DOMAIN-SUFFIX,sspai.com,DIRECT
  - DOMAIN-SUFFIX,suning.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,tenpay.com,DIRECT
  - DOMAIN-SUFFIX,tianyancha.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,tudou.com,DIRECT
  - DOMAIN-SUFFIX,umetrip.com,DIRECT
  - DOMAIN-SUFFIX,upaiyun.com,DIRECT
  - DOMAIN-SUFFIX,upyun.com,DIRECT
  - DOMAIN-SUFFIX,veryzhun.com,DIRECT
  - DOMAIN-SUFFIX,weather.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,xiami.com,DIRECT
  - DOMAIN-SUFFIX,xiami.net,DIRECT
  - DOMAIN-SUFFIX,xiaomicp.com,DIRECT
  - DOMAIN-SUFFIX,ximalaya.com,DIRECT
  - DOMAIN-SUFFIX,xmcdn.com,DIRECT
  - DOMAIN-SUFFIX,xunlei.com,DIRECT
  - DOMAIN-SUFFIX,yhd.com,DIRECT
  - DOMAIN-SUFFIX,yihaodianimg.com,DIRECT
  - DOMAIN-SUFFIX,yinxiang.com,DIRECT
  - DOMAIN-SUFFIX,ykimg.com,DIRECT
  - DOMAIN-SUFFIX,youdao.com,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,zealer.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,zhimg.com,DIRECT
  - DOMAIN-SUFFIX,zimuzu.tv,DIRECT
  - DOMAIN-SUFFIX,zoho.com,DIRECT
  - DOMAIN-KEYWORD,amazon,myNet
  - DOMAIN-KEYWORD,google,myNet
  - DOMAIN-KEYWORD,gmail,myNet
  - DOMAIN-KEYWORD,youtube,myNet
  - DOMAIN-KEYWORD,facebook,myNet
  - DOMAIN-SUFFIX,fb.me,myNet
  - DOMAIN-SUFFIX,fbcdn.net,myNet
  - DOMAIN-KEYWORD,twitter,myNet
  - DOMAIN-KEYWORD,instagram,myNet
  - DOMAIN-KEYWORD,dropbox,myNet
  - DOMAIN-SUFFIX,twimg.com,myNet
  - DOMAIN-KEYWORD,blogspot,myNet
  - DOMAIN-SUFFIX,youtu.be,myNet
  - DOMAIN-KEYWORD,whatsapp,myNet
  - DOMAIN-KEYWORD,admarvel,REJECT
  - DOMAIN-KEYWORD,admaster,REJECT
  - DOMAIN-KEYWORD,adsage,REJECT
  - DOMAIN-KEYWORD,adsmogo,REJECT
  - DOMAIN-KEYWORD,adsrvmedia,REJECT
  - DOMAIN-KEYWORD,adwords,REJECT
  - DOMAIN-KEYWORD,adservice,REJECT
  - DOMAIN-SUFFIX,appsflyer.com,REJECT
  - DOMAIN-KEYWORD,domob,REJECT
  - DOMAIN-SUFFIX,doubleclick.net,REJECT
  - DOMAIN-KEYWORD,duomeng,REJECT
  - DOMAIN-KEYWORD,dwtrack,REJECT
  - DOMAIN-KEYWORD,guanggao,REJECT
  - DOMAIN-KEYWORD,lianmeng,REJECT
  - DOMAIN-SUFFIX,mmstat.com,REJECT
  - DOMAIN-KEYWORD,mopub,REJECT
  - DOMAIN-KEYWORD,omgmta,REJECT
  - DOMAIN-KEYWORD,openx,REJECT
  - DOMAIN-KEYWORD,partnerad,REJECT
  - DOMAIN-KEYWORD,pingfore,REJECT
  - DOMAIN-KEYWORD,supersonicads,REJECT
  - DOMAIN-KEYWORD,uedas,REJECT
  - DOMAIN-KEYWORD,umeng,REJECT
  - DOMAIN-KEYWORD,usage,REJECT
  - DOMAIN-SUFFIX,vungle.com,REJECT
  - DOMAIN-KEYWORD,wlmonitor,REJECT
  - DOMAIN-KEYWORD,zjtoolbar,REJECT
  - DOMAIN-SUFFIX,9to5mac.com,myNet
  - DOMAIN-SUFFIX,abpchina.org,myNet
  - DOMAIN-SUFFIX,adblockplus.org,myNet
  - DOMAIN-SUFFIX,adobe.com,myNet
  - DOMAIN-SUFFIX,akamaized.net,myNet
  - DOMAIN-SUFFIX,alfredapp.com,myNet
  - DOMAIN-SUFFIX,amplitude.com,myNet
  - DOMAIN-SUFFIX,ampproject.org,myNet
  - DOMAIN-SUFFIX,android.com,myNet
  - DOMAIN-SUFFIX,angularjs.org,myNet
  - DOMAIN-SUFFIX,aolcdn.com,myNet
  - DOMAIN-SUFFIX,apkpure.com,myNet
  - DOMAIN-SUFFIX,appledaily.com,myNet
  - DOMAIN-SUFFIX,appshopper.com,myNet
  - DOMAIN-SUFFIX,appspot.com,myNet
  - DOMAIN-SUFFIX,arcgis.com,myNet
  - DOMAIN-SUFFIX,archive.org,myNet
  - DOMAIN-SUFFIX,armorgames.com,myNet
  - DOMAIN-SUFFIX,aspnetcdn.com,myNet
  - DOMAIN-SUFFIX,att.com,myNet
  - DOMAIN-SUFFIX,awsstatic.com,myNet
  - DOMAIN-SUFFIX,azureedge.net,myNet
  - DOMAIN-SUFFIX,azurewebsites.net,myNet
  - DOMAIN-SUFFIX,bing.com,myNet
  - DOMAIN-SUFFIX,bintray.com,myNet
  - DOMAIN-SUFFIX,bit.com,myNet
  - DOMAIN-SUFFIX,bit.ly,myNet
  - DOMAIN-SUFFIX,bitbucket.org,myNet
  - DOMAIN-SUFFIX,bjango.com,myNet
  - DOMAIN-SUFFIX,bkrtx.com,myNet
  - DOMAIN-SUFFIX,blog.com,myNet
  - DOMAIN-SUFFIX,blogcdn.com,myNet
  - DOMAIN-SUFFIX,blogger.com,myNet
  - DOMAIN-SUFFIX,blogsmithmedia.com,myNet
  - DOMAIN-SUFFIX,blogspot.com,myNet
  - DOMAIN-SUFFIX,blogspot.hk,myNet
  - DOMAIN-SUFFIX,bloomberg.com,myNet
  - DOMAIN-SUFFIX,box.com,myNet
  - DOMAIN-SUFFIX,box.net,myNet
  - DOMAIN-SUFFIX,cachefly.net,myNet
  - DOMAIN-SUFFIX,chromium.org,myNet
  - DOMAIN-SUFFIX,cl.ly,myNet
  - DOMAIN-SUFFIX,cloudflare.com,myNet
  - DOMAIN-SUFFIX,cloudfront.net,myNet
  - DOMAIN-SUFFIX,cloudmagic.com,myNet
  - DOMAIN-SUFFIX,cmail19.com,myNet
  - DOMAIN-SUFFIX,cnet.com,myNet
  - DOMAIN-SUFFIX,cocoapods.org,myNet
  - DOMAIN-SUFFIX,comodoca.com,myNet
  - DOMAIN-SUFFIX,crashlytics.com,myNet
  - DOMAIN-SUFFIX,culturedcode.com,myNet
  - DOMAIN-SUFFIX,d.pr,myNet
  - DOMAIN-SUFFIX,danilo.to,myNet
  - DOMAIN-SUFFIX,dayone.me,myNet
  - DOMAIN-SUFFIX,db.tt,myNet
  - DOMAIN-SUFFIX,deskconnect.com,myNet
  - DOMAIN-SUFFIX,disq.us,myNet
  - DOMAIN-SUFFIX,disqus.com,myNet
  - DOMAIN-SUFFIX,disquscdn.com,myNet
  - DOMAIN-SUFFIX,dnsimple.com,myNet
  - DOMAIN-SUFFIX,docker.com,myNet
  - DOMAIN-SUFFIX,dribbble.com,myNet
  - DOMAIN-SUFFIX,droplr.com,myNet
  - DOMAIN-SUFFIX,duckduckgo.com,myNet
  - DOMAIN-SUFFIX,dueapp.com,myNet
  - DOMAIN-SUFFIX,dytt8.net,myNet
  - DOMAIN-SUFFIX,edgecastcdn.net,myNet
  - DOMAIN-SUFFIX,edgekey.net,myNet
  - DOMAIN-SUFFIX,edgesuite.net,myNet
  - DOMAIN-SUFFIX,engadget.com,myNet
  - DOMAIN-SUFFIX,entrust.net,myNet
  - DOMAIN-SUFFIX,eurekavpt.com,myNet
  - DOMAIN-SUFFIX,evernote.com,myNet
  - DOMAIN-SUFFIX,fabric.io,myNet
  - DOMAIN-SUFFIX,fast.com,myNet
  - DOMAIN-SUFFIX,fastly.net,myNet
  - DOMAIN-SUFFIX,fc2.com,myNet
  - DOMAIN-SUFFIX,feedburner.com,myNet
  - DOMAIN-SUFFIX,feedly.com,myNet
  - DOMAIN-SUFFIX,feedsportal.com,myNet
  - DOMAIN-SUFFIX,fiftythree.com,myNet
  - DOMAIN-SUFFIX,firebaseio.com,myNet
  - DOMAIN-SUFFIX,flexibits.com,myNet
  - DOMAIN-SUFFIX,flickr.com,myNet
  - DOMAIN-SUFFIX,flipboard.com,myNet
  - DOMAIN-SUFFIX,g.co,myNet
  - DOMAIN-SUFFIX,gabia.net,myNet
  - DOMAIN-SUFFIX,geni.us,myNet
  - DOMAIN-SUFFIX,gfx.ms,myNet
  - DOMAIN-SUFFIX,ggpht.com,myNet
  - DOMAIN-SUFFIX,ghostnoteapp.com,myNet
  - DOMAIN-SUFFIX,git.io,myNet
  - DOMAIN-KEYWORD,github,myNet
  - DOMAIN-SUFFIX,globalsign.com,myNet
  - DOMAIN-SUFFIX,gmodules.com,myNet
  - DOMAIN-SUFFIX,godaddy.com,myNet
  - DOMAIN-SUFFIX,golang.org,myNet
  - DOMAIN-SUFFIX,gongm.in,myNet
  - DOMAIN-SUFFIX,goo.gl,myNet
  - DOMAIN-SUFFIX,goodreaders.com,myNet
  - DOMAIN-SUFFIX,goodreads.com,myNet
  - DOMAIN-SUFFIX,gravatar.com,myNet
  - DOMAIN-SUFFIX,gstatic.com,myNet
  - DOMAIN-SUFFIX,gvt0.com,myNet
  - DOMAIN-SUFFIX,hockeyapp.net,myNet
  - DOMAIN-SUFFIX,hotmail.com,myNet
  - DOMAIN-SUFFIX,icons8.com,myNet
  - DOMAIN-SUFFIX,ifixit.com,myNet
  - DOMAIN-SUFFIX,ift.tt,myNet
  - DOMAIN-SUFFIX,ifttt.com,myNet
  - DOMAIN-SUFFIX,iherb.com,myNet
  - DOMAIN-SUFFIX,imageshack.us,myNet
  - DOMAIN-SUFFIX,img.ly,myNet
  - DOMAIN-SUFFIX,imgur.com,myNet
  - DOMAIN-SUFFIX,imore.com,myNet
  - DOMAIN-SUFFIX,instapaper.com,myNet
  - DOMAIN-SUFFIX,ipn.li,myNet
  - DOMAIN-SUFFIX,is.gd,myNet
  - DOMAIN-SUFFIX,issuu.com,myNet
  - DOMAIN-SUFFIX,itgonglun.com,myNet
  - DOMAIN-SUFFIX,itun.es,myNet
  - DOMAIN-SUFFIX,ixquick.com,myNet
  - DOMAIN-SUFFIX,j.mp,myNet
  - DOMAIN-SUFFIX,js.revsci.net,myNet
  - DOMAIN-SUFFIX,jshint.com,myNet
  - DOMAIN-SUFFIX,jtvnw.net,myNet
  - DOMAIN-SUFFIX,justgetflux.com,myNet
  - DOMAIN-SUFFIX,kat.cr,myNet
  - DOMAIN-SUFFIX,klip.me,myNet
  - DOMAIN-SUFFIX,libsyn.com,myNet
  - DOMAIN-SUFFIX,linkedin.com,myNet
  - DOMAIN-SUFFIX,line-apps.com,myNet
  - DOMAIN-SUFFIX,linode.com,myNet
  - DOMAIN-SUFFIX,lithium.com,myNet
  - DOMAIN-SUFFIX,littlehj.com,myNet
  - DOMAIN-SUFFIX,live.com,myNet
  - DOMAIN-SUFFIX,live.net,myNet
  - DOMAIN-SUFFIX,livefilestore.com,myNet
  - DOMAIN-SUFFIX,llnwd.net,myNet
  - DOMAIN-SUFFIX,macid.co,myNet
  - DOMAIN-SUFFIX,macromedia.com,myNet
  - DOMAIN-SUFFIX,macrumors.com,myNet
  - DOMAIN-SUFFIX,mashable.com,myNet
  - DOMAIN-SUFFIX,mathjax.org,myNet
  - DOMAIN-SUFFIX,medium.com,myNet
  - DOMAIN-SUFFIX,mega.co.nz,myNet
  - DOMAIN-SUFFIX,mega.nz,myNet
  - DOMAIN-SUFFIX,megaupload.com,myNet
  - DOMAIN-SUFFIX,microsofttranslator.com,myNet
  - DOMAIN-SUFFIX,mindnode.com,myNet
  - DOMAIN-SUFFIX,mobile01.com,myNet
  - DOMAIN-SUFFIX,modmyi.com,myNet
  - DOMAIN-SUFFIX,msedge.net,myNet
  - DOMAIN-SUFFIX,myfontastic.com,myNet
  - DOMAIN-SUFFIX,name.com,myNet
  - DOMAIN-SUFFIX,nextmedia.com,myNet
  - DOMAIN-SUFFIX,nsstatic.net,myNet
  - DOMAIN-SUFFIX,nssurge.com,myNet
  - DOMAIN-SUFFIX,nyt.com,myNet
  - DOMAIN-SUFFIX,nytimes.com,myNet
  - DOMAIN-SUFFIX,omnigroup.com,myNet
  - DOMAIN-SUFFIX,onedrive.com,myNet
  - DOMAIN-SUFFIX,onenote.com,myNet
  - DOMAIN-SUFFIX,ooyala.com,myNet
  - DOMAIN-SUFFIX,openvpn.net,myNet
  - DOMAIN-SUFFIX,openwrt.org,myNet
  - DOMAIN-SUFFIX,orkut.com,myNet
  - DOMAIN-SUFFIX,osxdaily.com,myNet
  - DOMAIN-SUFFIX,outlook.com,myNet
  - DOMAIN-SUFFIX,ow.ly,myNet
  - DOMAIN-SUFFIX,paddleapi.com,myNet
  - DOMAIN-SUFFIX,parallels.com,myNet
  - DOMAIN-SUFFIX,parse.com,myNet
  - DOMAIN-SUFFIX,pdfexpert.com,myNet
  - DOMAIN-SUFFIX,periscope.tv,myNet
  - DOMAIN-SUFFIX,pinboard.in,myNet
  - DOMAIN-SUFFIX,pinterest.com,myNet
  - DOMAIN-SUFFIX,pixelmator.com,myNet
  - DOMAIN-SUFFIX,pixiv.net,myNet
  - DOMAIN-SUFFIX,playpcesor.com,myNet
  - DOMAIN-SUFFIX,playstation.com,myNet
  - DOMAIN-SUFFIX,playstation.com.hk,myNet
  - DOMAIN-SUFFIX,playstation.net,myNet
  - DOMAIN-SUFFIX,playstationnetwork.com,myNet
  - DOMAIN-SUFFIX,pushwoosh.com,myNet
  - DOMAIN-SUFFIX,rime.im,myNet
  - DOMAIN-SUFFIX,servebom.com,myNet
  - DOMAIN-SUFFIX,sfx.ms,myNet
  - DOMAIN-SUFFIX,shadowsocks.org,myNet
  - DOMAIN-SUFFIX,sharethis.com,myNet
  - DOMAIN-SUFFIX,shazam.com,myNet
  - DOMAIN-SUFFIX,skype.com,myNet
  - DOMAIN-SUFFIX,smartdnsmyNet.com,myNet
  - DOMAIN-SUFFIX,smartmailcloud.com,myNet
  - DOMAIN-SUFFIX,sndcdn.com,myNet
  - DOMAIN-SUFFIX,sony.com,myNet
  - DOMAIN-SUFFIX,soundcloud.com,myNet
  - DOMAIN-SUFFIX,sourceforge.net,myNet
  - DOMAIN-SUFFIX,spotify.com,myNet
  - DOMAIN-SUFFIX,squarespace.com,myNet
  - DOMAIN-SUFFIX,sstatic.net,myNet
  - DOMAIN-SUFFIX,st.luluku.pw,myNet
  - DOMAIN-SUFFIX,stackoverflow.com,myNet
  - DOMAIN-SUFFIX,startpage.com,myNet
  - DOMAIN-SUFFIX,staticflickr.com,myNet
  - DOMAIN-SUFFIX,steamcommunity.com,myNet
  - DOMAIN-SUFFIX,symauth.com,myNet
  - DOMAIN-SUFFIX,symcb.com,myNet
  - DOMAIN-SUFFIX,symcd.com,myNet
  - DOMAIN-SUFFIX,tapbots.com,myNet
  - DOMAIN-SUFFIX,tapbots.net,myNet
  - DOMAIN-SUFFIX,tdesktop.com,myNet
  - DOMAIN-SUFFIX,techcrunch.com,myNet
  - DOMAIN-SUFFIX,techsmith.com,myNet
  - DOMAIN-SUFFIX,thepiratebay.org,myNet
  - DOMAIN-SUFFIX,theverge.com,myNet
  - DOMAIN-SUFFIX,time.com,myNet
  - DOMAIN-SUFFIX,timeinc.net,myNet
  - DOMAIN-SUFFIX,tiny.cc,myNet
  - DOMAIN-SUFFIX,tinypic.com,myNet
  - DOMAIN-SUFFIX,tmblr.co,myNet
  - DOMAIN-SUFFIX,todoist.com,myNet
  - DOMAIN-SUFFIX,trello.com,myNet
  - DOMAIN-SUFFIX,trustasiassl.com,myNet
  - DOMAIN-SUFFIX,tumblr.co,myNet
  - DOMAIN-SUFFIX,tumblr.com,myNet
  - DOMAIN-SUFFIX,tweetdeck.com,myNet
  - DOMAIN-SUFFIX,tweetmarker.net,myNet
  - DOMAIN-SUFFIX,twitch.tv,myNet
  - DOMAIN-SUFFIX,txmblr.com,myNet
  - DOMAIN-SUFFIX,typekit.net,myNet
  - DOMAIN-SUFFIX,ubertags.com,myNet
  - DOMAIN-SUFFIX,ublock.org,myNet
  - DOMAIN-SUFFIX,ubnt.com,myNet
  - DOMAIN-SUFFIX,ulyssesapp.com,myNet
  - DOMAIN-SUFFIX,urchin.com,myNet
  - DOMAIN-SUFFIX,usertrust.com,myNet
  - DOMAIN-SUFFIX,v.gd,myNet
  - DOMAIN-SUFFIX,v2ex.com,myNet
  - DOMAIN-SUFFIX,vimeo.com,myNet
  - DOMAIN-SUFFIX,vimeocdn.com,myNet
  - DOMAIN-SUFFIX,vine.co,myNet
  - DOMAIN-SUFFIX,vivaldi.com,myNet
  - DOMAIN-SUFFIX,vox-cdn.com,myNet
  - DOMAIN-SUFFIX,vsco.co,myNet
  - DOMAIN-SUFFIX,vultr.com,myNet
  - DOMAIN-SUFFIX,w.org,myNet
  - DOMAIN-SUFFIX,w3schools.com,myNet
  - DOMAIN-SUFFIX,webtype.com,myNet
  - DOMAIN-SUFFIX,wikiwand.com,myNet
  - DOMAIN-SUFFIX,wikileaks.org,myNet
  - DOMAIN-SUFFIX,wikimedia.org,myNet
  - DOMAIN-SUFFIX,wikipedia.com,myNet
  - DOMAIN-SUFFIX,wikipedia.org,myNet
  - DOMAIN-SUFFIX,windows.com,myNet
  - DOMAIN-SUFFIX,windows.net,myNet
  - DOMAIN-SUFFIX,wire.com,myNet
  - DOMAIN-SUFFIX,wordpress.com,myNet
  - DOMAIN-SUFFIX,workflowy.com,myNet
  - DOMAIN-SUFFIX,wp.com,myNet
  - DOMAIN-SUFFIX,wsj.com,myNet
  - DOMAIN-SUFFIX,wsj.net,myNet
  - DOMAIN-SUFFIX,xda-developers.com,myNet
  - DOMAIN-SUFFIX,xeeno.com,myNet
  - DOMAIN-SUFFIX,xiti.com,myNet
  - DOMAIN-SUFFIX,yahoo.com,myNet
  - DOMAIN-SUFFIX,yimg.com,myNet
  - DOMAIN-SUFFIX,ying.com,myNet
  - DOMAIN-SUFFIX,yoyo.org,myNet
  - DOMAIN-SUFFIX,ytimg.com,myNet
  - DOMAIN-SUFFIX,telegra.ph,myNet
  - DOMAIN-SUFFIX,telegram.org,myNet
  - IP-CIDR,91.108.4.0/22,myNet,no-resolve
  - IP-CIDR,91.108.8.0/21,myNet,no-resolve
  - IP-CIDR,91.108.16.0/22,myNet,no-resolve
  - IP-CIDR,91.108.56.0/22,myNet,no-resolve
  - IP-CIDR,149.154.160.0/20,myNet,no-resolve
  - IP-CIDR6,2001:67c:4e8::/48,myNet,no-resolve
  - IP-CIDR6,2001:b28:f23d::/48,myNet,no-resolve
  - IP-CIDR6,2001:b28:f23f::/48,myNet,no-resolve
  - IP-CIDR,120.232.181.162/32,myNet,no-resolve
  - IP-CIDR,120.241.147.226/32,myNet,no-resolve
  - IP-CIDR,120.253.253.226/32,myNet,no-resolve
  - IP-CIDR,120.253.255.162/32,myNet,no-resolve
  - IP-CIDR,120.253.255.34/32,myNet,no-resolve
  - IP-CIDR,120.253.255.98/32,myNet,no-resolve
  - IP-CIDR,180.163.150.162/32,myNet,no-resolve
  - IP-CIDR,180.163.150.34/32,myNet,no-resolve
  - IP-CIDR,180.163.151.162/32,myNet,no-resolve
  - IP-CIDR,180.163.151.34/32,myNet,no-resolve
  - IP-CIDR,203.208.39.0/24,myNet,no-resolve
  - IP-CIDR,203.208.40.0/24,myNet,no-resolve
  - IP-CIDR,203.208.41.0/24,myNet,no-resolve
  - IP-CIDR,203.208.43.0/24,myNet,no-resolve
  - IP-CIDR,203.208.50.0/24,myNet,no-resolve
  - IP-CIDR,220.181.174.162/32,myNet,no-resolve
  - IP-CIDR,220.181.174.226/32,myNet,no-resolve
  - IP-CIDR,220.181.174.34/32,myNet,no-resolve
  - DOMAIN,injections.adguard.org,DIRECT
  - DOMAIN,local.adguard.org,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,-cn,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,myNet
